import { ArrowUpLeft, MapPin, Clock, Phone, MessageCircle } from "lucide-react";
const branches = [
 {name:"فرع الشفا",neighborhood:"حي الشفا",address:"شارع التخصصي",hours:"٣:٣٠ م – ١١ م",phone:"+966552202321",mapsUrl:"https://maps.app.goo.gl/QCTbRkfCXXZmcQr3A"},
 {name:"فرع الطائف",neighborhood:"الطائف",address:"طريق الملك عبدالله",hours:"٤:٠٠ م – ١١ م",phone:"+966500462668",mapsUrl:"https://maps.app.goo.gl/FHAz8E6RCYn3DUWY7"}
];
export function OrderCTA() {
 return <>
 <section id="order" className="mm-order"><div className="mm-container mm-order-inner"><div><p className="mm-eyebrow">LET’S MAKE IT MEMORABLE</p><h2>لديك مناسبة قريبة؟<br/><em>نضيف لها الحلاوة.</em></h2><p>حدّثنا عن مناسبتك، ودعنا نساعدك في اختيار الباقة<br className="hidden sm:block"/> والحشوات والتقديم الذي يليق بها.</p></div><a className="mm-button mm-button-gold" href="https://wa.me/966552202321" target="_blank" rel="noopener noreferrer"><MessageCircle size={19}/> نسّق مناسبتك عبر واتساب <ArrowUpLeft size={18}/></a></div><span className="mm-order-watermark" aria-hidden="true">More.</span></section>
 <section id="branches" className="mm-section mm-branches" aria-labelledby="branches-title"><div className="mm-container"><div className="mm-section-heading"><div><p className="mm-eyebrow">COME A LITTLE CLOSER</p><h2 id="branches-title">الحلاوة <em>بالقرب منك.</em></h2></div><p>يسعدنا لقاؤك.<br/>اكتشف أقرب فروعنا، ودع الحواس تختار.</p></div><div className="mm-branches-grid">{branches.map((branch,index)=><article className="mm-branch-card" key={branch.name}><div className="mm-branch-visual" aria-hidden="true"><div className="mm-map-street mm-map-street-one"/><div className="mm-map-street mm-map-street-two"/><div className="mm-map-street mm-map-street-three"/><span className="mm-map-pin"><MapPin size={29}/></span><span className="mm-map-label" dir="ltr">MELT MORE</span><span className="mm-map-caption">رسم توضيحي · الموقع الدقيق عبر الخرائط</span></div><div className="mm-branch-info"><div className="mm-branch-title"><div><p className="mm-eyebrow">VISIT US · 0{index+1}</p><h3>{branch.name}</h3></div><span>{branch.neighborhood}</span></div><p><MapPin size={16}/>{branch.address}</p><p><Clock size={16}/>{branch.hours}</p><a className="mm-branch-phone" href={`tel:${branch.phone}`}><Phone size={16}/><span dir="ltr">{branch.phone}</span></a><div className="mm-branch-actions"><a href={branch.mapsUrl} target="_blank" rel="noopener noreferrer">الاتجاهات على الخريطة <ArrowUpLeft size={17}/></a><a href={`https://wa.me/${branch.phone.replace(/\D/g,"")}`} target="_blank" rel="noopener noreferrer" aria-label={`واتساب ${branch.name}`}><MessageCircle size={19}/></a></div></div></article>)}</div></div></section>
 </>;
}
